version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: task-management-mysql
    restart: always
    env_file:
      - .env
    volumes:
      - database:/data/mysql
    ports:
      - '3306:3306'
volumes:
  database: