version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: task-management-postgred
    restart: always
    env_file:
      - .env.dev
    volumes:
      - database:/data/postgres
    ports:
      - '5433:5432'
volumes:
  database: